### ISSUE TITLE
about Box2Mask-C

### ISSUE THREAD

**Issue by MiSsU-HH** [LiWentomng/BoxInstSeg#20]
Hello, thanks for your contribution~ I have a issue about Box2Mask-C and BoxLevelSet:
I noticed in the paper that there seems to be no difference between Box2Mask-C and BoxLevelset (except the local consistency module ). However, why does Box2Mask-C outperform BoxLevelset? Are there any differences between the two? Can you provide the configuration file for Box2Mask-C?

**Comment by LiWentomng** [comment]
@MiSsU-HH  Hello,  thanks for your question. 
Yes, the difference between Box2Mask-C and BoxLevelset lie on the local consistency module, which brings the performance gain and make Box2Mask-C outperform BoxLevelset.   The configuration is same to Boxlevelset, and add the the code of local consistency module during the training.

**Comment by MiSsU-HH** [comment]
I see, thanks for your answer~
