### ISSUE TITLE
Custom dataset in coco format, Commands to run

### ISSUE THREAD

**Issue by VikasRajashekar** [LiWentomng/BoxInstSeg#5]
First of all very cool work.

I would like to know for my dataset in coco format with just one class, I would like to try your model. 

1. Do you recommend any changes other than num_classes? 

2. Also what is num_things_classes=80,num_stuff_classes=0, in box2Mask? 

3. Also the commands to  run are the same as mmdetection right?

**Comment by LiWentomng** [comment]
Hello @VikasRajashekar  

1. The `num_classes` in the config file needs three places need to be changed, such as the line 23, line 94 and line 103 in this [confg](https://github.com/LiWentomng/BoxInstSeg/blob/main/configs/box2mask/box2mask_r50_lsj_8x2_50e_coco.py).
     Besides the num_classes, you  also need to change the `training step` and `max_iters`, according to the number of your training images to satisfy the 50 epoch.

2. Our model is based on MaskFormer framework, which can achieve the panoptic segmentation. In the box2mask, we only do the instance segmentation, so num_stuff_classes=0. We also explore the box2mask to achieve the panoptic segmentation recently.

3. Yes, the commands are same as the mmdetection.

**Comment by VikasRajashekar** [comment]
@LiWentomng Thanks for the reply. I almost got it to run but facing the following issue.
```
"File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/focal_loss.py", line 56, in forward
    ext_module.sigmoid_focal_loss_forward(
RuntimeError: sigmoid_focal_loss_forward_impl: implementation for device cuda:7 not found."
```
what is mmcv version you used? 
I am using 1.5.0.

Any help to resolve this issue would be of great help.

**Comment by LiWentomng** [comment]
@VikasRajashekar  
It seems your installed mmcv-full is not compatible with your envs.
You can try to re-install mmcv-full by the following, 
```
pip install -U openmim
mim install mmcv-full==1.5.0
```

**Comment by VikasRajashekar** [comment]
@LiWentomng I am using the right version of mmcv I believe. 

```
TorchVision: 0.10.0a0
OpenCV: 3.4.11
MMCV: 1.5.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: not available
MMDetection: 2.25.0+
```
Do I need to compile it?

**Comment by VikasRajashekar** [comment]
Closing the issue as I am able to run after building it from the source.
